language: java

os: linux

jdk:
  - oraclejdk11
  - oraclejdk12
  - oraclejdk13
  - oraclejdk14
  - oraclejdk15
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
  - openjdk15

install: skip

script: ./gradlew build -x test

cache:
  directories:
    - $HOME/.gradle
