language: java

os: linux

jdk:
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
  - openjdk15
  - openjdk16
  - openjdk17

install: skip

script: ./gradlew build -x test

cache:
  directories:
    - $HOME/.gradle
